# Generated by Django 5.2.7 on 2026-01-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_view', '0002_university_profile_created_at_department'),
        ('uni_home_page', '0003_aimessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='uni_home_page.university'),
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profile_view.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='uni_home_page.university'),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
